name: Deploy Firebase Functions and Hosting

on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'
      
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  deploy-functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: npm install
        working-directory: ./functions

      - name: Authenticate with Workload Identity Federation
        uses: google-github-actions/auth@v2
        with: 
           workload_identity_provider: projects/314758267226/locations/global/workloadIdentityPools/github-pool/providers/github
           service_account: firebase-auth@dynamic-array-resume-builder.iam.gserviceaccount.com
       
      - name: Deploy Firebase Functions
        run: firebase deploy --only functions

  
